-- =========================================================
-- AWESOME CHOCOLATES - COMPLETE SQL PRACTICE
-- =========================================================
DROP DATABASE IF EXISTS `awesome chocolates`;
CREATE DATABASE `awesome chocolates`;
USE `awesome chocolates`;


-- =========================================================
-- 1. CHECK DATABASE AND TABLES
-- =========================================================

SHOW TABLES;

SELECT * FROM sales;
SELECT * FROM products;
SELECT * FROM people;
SELECT * FROM geo;

DESC sales;
DESC products;
DESC people;
DESC geo;


-- =========================================================
--- 3. BASIC AGGREGATION QUESTIONS
-- =========================================================


-- 1. Find the total sales amount generated by the company.

SELECT SUM(amount) AS total_sales
FROM sales;


-- 2. Find the total number of customers served.

SELECT SUM(customers) AS total_customers
FROM sales;


-- 3. Find the total number of boxes sold.

SELECT SUM(boxes) AS total_boxes_sold
FROM sales;


-- 4. Find the average sales amount per transaction.

SELECT AVG(amount) AS average_sales
FROM sales;


-- =========================================================
-- 4. SALES TRANSACTION QUESTIONS
-- =========================================================


-- 5. Display the top 10 highest sales transactions.

SELECT *
FROM sales
ORDER BY amount DESC
LIMIT 10;


-- 6. Find total sales for each product.

SELECT
    PID,
    SUM(amount) AS total_sales
FROM sales
GROUP BY PID;


-- 7. Find the top 5 products based on total sales amount.

SELECT
    PID,
    SUM(amount) AS total_sales
FROM sales
GROUP BY PID
ORDER BY total_sales DESC
LIMIT 5;


-- =========================================================
-- 5. PRODUCT ANALYSIS
-- =========================================================


-- 8. Find total boxes sold for each product category.

SELECT
    p.category,
    SUM(s.boxes) AS total_boxes_sold
FROM sales s
JOIN products p
    ON s.PID = p.PID
GROUP BY p.category;


-- 9. Find which product generated the highest total sales.

SELECT
    PID,
    SUM(amount) AS total_sales
FROM sales
GROUP BY PID
ORDER BY total_sales DESC
LIMIT 1;


-- 10. Compare total sales between different product sizes.

SELECT
    p.size,
    SUM(s.amount) AS total_sales
FROM sales s
JOIN products p
    ON s.PID = p.PID
GROUP BY p.size;


-- 11. Find the average sales amount for each product category.

SELECT
    p.category,
    AVG(s.amount) AS average_sales_amount
FROM sales s
JOIN products p
    ON s.PID = p.PID
GROUP BY p.category;


-- =========================================================
-- 6. COUNTRY AND REGION ANALYSIS
-- =========================================================


-- 12. Find total sales by country.

SELECT
    g.geo,
    SUM(s.amount) AS total_sales
FROM sales s
JOIN geo g
    ON s.GeoID = g.GeoID
GROUP BY g.geo;


-- 13. Find total sales by region.

SELECT
    g.region,
    SUM(s.amount) AS total_sales
FROM sales s
JOIN geo g
    ON s.GeoID = g.GeoID
GROUP BY g.region;


-- 14. Which country generated the highest total sales?

SELECT
    g.geo,
    SUM(s.amount) AS total_sales
FROM sales s
JOIN geo g
    ON s.GeoID = g.GeoID
GROUP BY g.geo
ORDER BY total_sales DESC
LIMIT 1;


-- 15. Find the total number of customers by country.

SELECT
    g.geo,
    SUM(s.customers) AS total_customers
FROM sales s
JOIN geo g
    ON s.GeoID = g.GeoID
GROUP BY g.geo;


-- =========================================================
-- 7. SALESPERSON ANALYSIS
-- =========================================================


-- 16. Find the total sales generated by each salesperson.

SELECT
    p.salesperson,
    SUM(s.amount) AS total_sales
FROM sales s
JOIN people p
    ON s.SPID = p.SPID
GROUP BY p.salesperson;


-- 17. Find the top 5 best-performing salespersons
--     based on sales amount.

SELECT
    p.salesperson,
    SUM(s.amount) AS sales_amount
FROM sales s
JOIN people p
    ON s.SPID = p.SPID
GROUP BY p.salesperson
ORDER BY sales_amount DESC
LIMIT 5;


-- 18. Find the total boxes sold by each salesperson.

SELECT
    p.salesperson,
    SUM(s.boxes) AS total_boxes
FROM sales s
JOIN people p
    ON s.SPID = p.SPID
GROUP BY p.salesperson;


-- =========================================================
-- 8. WHERE + GROUP BY + HAVING
-- =========================================================


-- 19. Find each product's total sales,
--     considering only transactions where
--     Amount > 1,000 OR Customers > 20,
--     and sort highest first.

SELECT
    PID,
    SUM(amount) AS total_sales
FROM sales
WHERE amount > 1000
   OR customers > 20
GROUP BY PID
ORDER BY total_sales DESC;


-- 20. Find each salesperson's average sales amount,
--     considering only transactions where
--     Amount > 1,000 AND Boxes > 10,
--     and display the top 5.

SELECT
    p.salesperson,
    AVG(s.amount) AS average_sales_amount,
    SUM(s.boxes) AS total_boxes
FROM sales s
JOIN people p
    ON s.SPID = p.SPID
WHERE s.amount > 1000
  AND s.boxes > 10
GROUP BY p.salesperson
ORDER BY average_sales_amount DESC
LIMIT 5;


